# Generated by Django 6.0.4 on 2026-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bill_name", models.TextField()),
                ("bill_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bill_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ministry_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bill_year", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LokSabhaAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mpsno", models.IntegerField(blank=True, null=True)),
                ("member_name", models.CharField(max_length=255)),
                (
                    "constituency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("state_code", models.CharField(blank=True, max_length=10, null=True)),
                ("signed_days_count", models.IntegerField(default=0)),
                ("division", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MLA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_ut", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "constituency_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "constituency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("member", models.CharField(max_length=255)),
                ("party", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("member_profile", models.TextField(blank=True, null=True)),
                ("party_color", models.CharField(blank=True, max_length=50, null=True)),
                ("is_minister", models.CharField(default="No", max_length=10)),
                ("portfolio", models.TextField(blank=True, null=True)),
                ("is_chief_minister", models.CharField(default="No", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="RajyaSabhaAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.IntegerField(blank=True, null=True)),
                ("mpsno", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("div_no", models.CharField(blank=True, max_length=50, null=True)),
                ("state_code", models.CharField(blank=True, max_length=10, null=True)),
                ("no_of_sittings", models.IntegerField(default=0)),
            ],
        ),
    ]
