# Generated by Django 6.0.4 on 2026-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Governor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("governor_name", models.CharField(max_length=255)),
                (
                    "took_office",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
