from PIL import Image, ImageDraw, ImageFont
import textwrap
import io

def create_policy_poster(topic: str, summary: str, sentiment: str):
    """
    Generates a social media poster for a policy debate.
    Returns the image as bytes.
    """
    # 1. Setup Canvas (1080x1080 for Instagram)
    width, height = 1080, 1080
    
    # Choose Color based on Sentiment
    if "Positive" in sentiment:
        bg_color = "#E8F5E9"  # Light Green
        accent_color = "#2E7D32" # Dark Green
    elif "Negative" in sentiment:
        bg_color = "#FFEBEE"  # Light Red
        accent_color = "#C62828" # Dark Red
    else:
        bg_color = "#E3F2FD"  # Light Blue
        accent_color = "#1565C0" # Dark Blue

    img = Image.new('RGB', (width, height), color=bg_color)
    draw = ImageDraw.Draw(img)

    # 2. Draw Header
    draw.rectangle([(0, 0), (width, 150)], fill=accent_color)
    
    # Load Fonts (Using default if custom not found)
    try:
        # Try to use a nice font if available (e.g., Arial)
        font_header = ImageFont.truetype("arial.ttf", 80)
        font_text = ImageFont.truetype("arial.ttf", 50)
        font_small = ImageFont.truetype("arial.ttf", 30)
    except:
        font_header = ImageFont.load_default()
        font_text = ImageFont.load_default()
        font_small = ImageFont.load_default()

    # Write Topic (Title)
    draw.text((50, 40), f"PARLIAMENT WATCH: {topic.upper()}", fill="white", font=font_header)

    # 3. Write Summary Body
    # Wrap text so it doesn't go off screen
    wrapped_text = textwrap.fill(summary, width=40) 
    draw.text((100, 300), wrapped_text, fill="black", font=font_text)

    # 4. Write Sentiment Badge
    draw.rectangle([(100, 800), (500, 900)], fill=accent_color)
    draw.text((150, 830), f"Verdict: {sentiment}", fill="white", font=font_text)

    # 5. Footer
    draw.text((350, 1000), "Generated by Citizen Policy Intelligence AI", fill="gray", font=font_small)

    # 6. Save to Memory (not disk) to return via API
    img_byte_arr = io.BytesIO()
    img.save(img_byte_arr, format='PNG')
    img_byte_arr.seek(0)
    
    return img_byte_arr
