export const NEWS_FEEDS: Record<string, string> = {
    "nation": "https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en",
    "Andhra Pradesh": "https://news.google.com/rss/search?q=Andhra+Pradesh&hl=en-IN&gl=IN&ceid=IN:en",
    "Arunachal Pradesh": "https://news.google.com/rss/search?q=Arunachal+Pradesh&hl=en-IN&gl=IN&ceid=IN:en",
    "Assam": "https://news.google.com/rss/search?q=Assam&hl=en-IN&gl=IN&ceid=IN:en",
    "Bihar": "https://news.google.com/rss/search?q=Bihar&hl=en-IN&gl=IN&ceid=IN:en",
    "Chhattisgarh": "https://news.google.com/rss/search?q=Chhattisgarh&hl=en-IN&gl=IN&ceid=IN:en",
    "Goa": "https://news.google.com/rss/search?q=Goa+India&hl=en-IN&gl=IN&ceid=IN:en",
    "Gujarat": "https://news.google.com/rss/search?q=Gujarat&hl=en-IN&gl=IN&ceid=IN:en",
    "Haryana": "https://news.google.com/rss/search?q=Haryana&hl=en-IN&gl=IN&ceid=IN:en",
    "Himachal Pradesh": "https://news.google.com/rss/search?q=Himachal+Pradesh&hl=en-IN&gl=IN&ceid=IN:en",
    "Jharkhand": "https://news.google.com/rss/search?q=Jharkhand&hl=en-IN&gl=IN&ceid=IN:en",
    "Karnataka": "https://news.google.com/rss/search?q=Karnataka&hl=en-IN&gl=IN&ceid=IN:en",
    "Kerala": "https://news.google.com/rss/search?q=Kerala&hl=en-IN&gl=IN&ceid=IN:en",
    "Madhya Pradesh": "https://news.google.com/rss/search?q=Madhya+Pradesh&hl=en-IN&gl=IN&ceid=IN:en",
    "Maharashtra": "https://news.google.com/rss/search?q=Maharashtra&hl=en-IN&gl=IN&ceid=IN:en",
    "Manipur": "https://news.google.com/rss/search?q=Manipur&hl=en-IN&gl=IN&ceid=IN:en",
    "Meghalaya": "https://news.google.com/rss/search?q=Meghalaya&hl=en-IN&gl=IN&ceid=IN:en",
    "Mizoram": "https://news.google.com/rss/search?q=Mizoram&hl=en-IN&gl=IN&ceid=IN:en",
    "Nagaland": "https://news.google.com/rss/search?q=Nagaland&hl=en-IN&gl=IN&ceid=IN:en",
    "Odisha": "https://news.google.com/rss/search?q=Odisha&hl=en-IN&gl=IN&ceid=IN:en",
    "Punjab": "https://news.google.com/rss/search?q=Punjab+India&hl=en-IN&gl=IN&ceid=IN:en",
    "Rajasthan": "https://news.google.com/rss/search?q=Rajasthan&hl=en-IN&gl=IN&ceid=IN:en",
    "Sikkim": "https://news.google.com/rss/search?q=Sikkim&hl=en-IN&gl=IN&ceid=IN:en",
    "Tamil Nadu": "https://news.google.com/rss/search?q=Tamil+Nadu&hl=en-IN&gl=IN&ceid=IN:en",
    "Telangana": "https://news.google.com/rss/search?q=Telangana&hl=en-IN&gl=IN&ceid=IN:en",
    "Tripura": "https://news.google.com/rss/search?q=Tripura&hl=en-IN&gl=IN&ceid=IN:en",
    "Uttar Pradesh": "https://news.google.com/rss/search?q=Uttar+Pradesh&hl=en-IN&gl=IN&ceid=IN:en",
    "Uttarakhand": "https://news.google.com/rss/search?q=Uttarakhand&hl=en-IN&gl=IN&ceid=IN:en",
    "West Bengal": "https://news.google.com/rss/search?q=West+Bengal&hl=en-IN&gl=IN&ceid=IN:en",
    "Andaman & Nicobar Islands": "https://news.google.com/rss/search?q=Andaman+Nicobar&hl=en-IN&gl=IN&ceid=IN:en",
    "Chandigarh": "https://news.google.com/rss/search?q=Chandigarh&hl=en-IN&gl=IN&ceid=IN:en",
    "Dadra & Nagar Haveli and Daman & Diu": "https://news.google.com/rss/search?q=Dadra+Nagar+Haveli+Daman+Diu&hl=en-IN&gl=IN&ceid=IN:en",
    "Delhi (NCT)": "https://news.google.com/rss/search?q=Delhi+India&hl=en-IN&gl=IN&ceid=IN:en",
    "Jammu & Kashmir": "https://news.google.com/rss/search?q=Jammu+Kashmir&hl=en-IN&gl=IN&ceid=IN:en",
    "Ladakh": "https://news.google.com/rss/search?q=Ladakh&hl=en-IN&gl=IN&ceid=IN:en",
    "Lakshadweep": "https://news.google.com/rss/search?q=Lakshadweep&hl=en-IN&gl=IN&ceid=IN:en",
    "Puducherry": "https://news.google.com/rss/search?q=Puducherry&hl=en-IN&gl=IN&ceid=IN:en"
};
